import type { Metadata } from 'next'
import Link from 'next/link'
import { Navbar } from '@/components/navbar'
import { Zap, ArrowRight } from 'lucide-react'

export const metadata: Metadata = {
  title: 'About — withPOISE',
  description: 'withPOISE is an AI-powered objection response generator built on the proprietary POISE framework. Built for B2B consultants and agency owners who refuse to discount.',
  openGraph: {
    title: 'About — withPOISE',
    description: 'The story and mission behind withPOISE — AI-powered price objection handling for B2B consultants.',
    images: [{ url: '/opengraph-image', width: 1200, height: 630 }],
  },
}

const ABOUT_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'AboutPage',
  name: 'About withPOISE',
  url: 'https://withpoise.net/about',
  description: 'withPOISE is an AI-powered objection response generator built on the proprietary POISE framework, designed for B2B consultants and agency owners.',
  mainEntity: {
    '@type': 'Organization',
    name: 'withPOISE',
    url: 'https://withpoise.net',
    foundingDate: '2025',
    description: 'AI-powered price objection response generator for B2B consultants, built on the POISE framework.',
    contactPoint: { '@type': 'ContactPoint', email: 'hello@withpoise.net', contactType: 'customer support' },
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'Teiu 36',
      addressRegion: 'Argeș',
      addressCountry: 'RO',
    },
    legalName: 'PFA Dobre N Ana-Daniela',
  },
}

const POISE_STEPS = [
  { letter: 'P', name: 'Acknowledge', color: '#6366f1', desc: 'Validate the client\'s concern without giving ground. Show them they were heard.' },
  { letter: 'O', name: 'Reframe', color: '#8b5cf6', desc: 'Shift the conversation from cost to value, outcomes, and ROI.' },
  { letter: 'I', name: 'Logic of Decision', color: '#a78bfa', desc: 'Give the client a rational business framework for making their choice.' },
  { letter: 'S', name: 'Set Boundary', color: '#f59e0b', desc: 'Protect your pricing firmly and without apology.' },
  { letter: 'E', name: 'Next Step', color: '#10b981', desc: 'End with a single, clear, forward-moving action.' },
]

export default function AboutPage() {
  return (
    <div className="min-h-screen">
      <Navbar />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(ABOUT_SCHEMA) }} />

      <div className="max-w-3xl mx-auto px-4 py-20">

        {/* Header */}
        <div className="mb-14">
          <div className="inline-flex items-center gap-2 mb-6">
            <Zap className="w-6 h-6 text-[var(--color-primary)]" />
            <span className="font-bold text-xl text-[var(--color-text)]">with<span className="text-[var(--color-primary)]">POISE</span></span>
          </div>
          <h1 className="text-4xl font-bold text-[var(--color-text)] mb-4">
            Built for consultants who refuse to discount.
          </h1>
          <p className="text-lg text-[var(--color-text-muted)] leading-relaxed">
            withPOISE is an AI-powered tool that generates strategic, ready-to-send responses to price objections — built on a proprietary 5-step framework that holds your rate, reframes the conversation, and moves deals forward. No discounting. Ever.
          </p>
        </div>

        {/* Mission */}
        <div className="card mb-10">
          <h2 className="text-xl font-bold text-[var(--color-text)] mb-3">Why we built this</h2>
          <div className="space-y-4 text-[var(--color-text-muted)] leading-relaxed">
            <p>
              Most consultants and agency owners are good at what they do. They know their craft, they deliver results, and they have every reason to charge what they charge. But when a client pushes back on price, something breaks down. The instinct to defend, justify, or cave kicks in — and deals that should close at full rate get discounted or lost.
            </p>
            <p>
              The problem isn't confidence. It's structure. When you're in the moment, under pressure, with a deal on the line, having the right words is genuinely hard. That's what withPOISE solves.
            </p>
            <p>
              We built a framework — POISE — specifically for high-ticket B2B objection handling, and an AI engine that applies it to your exact situation in seconds. The result is a response that's strategic, firm, and tailored — not generic, not aggressive, and never discount-suggesting.
            </p>
          </div>
        </div>

        {/* The POISE Framework */}
        <div className="mb-10">
          <h2 className="text-xl font-bold text-[var(--color-text)] mb-6">The POISE Framework</h2>
          <p className="text-[var(--color-text-muted)] mb-6">
            Every response generated by withPOISE follows the same 5-step structure. Each step serves a specific purpose in moving the conversation from objection to close.
          </p>
          <div className="space-y-3">
            {POISE_STEPS.map(step => (
              <div key={step.letter} className="flex gap-4 p-4 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)]">
                <div className="flex-shrink-0 w-9 h-9 rounded-lg flex items-center justify-center font-bold text-white text-sm" style={{ backgroundColor: step.color }}>
                  {step.letter}
                </div>
                <div>
                  <p className="font-semibold text-[var(--color-text)] text-sm mb-0.5">{step.name}</p>
                  <p className="text-sm text-[var(--color-text-muted)]">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* What it handles */}
        <div className="card mb-10">
          <h2 className="text-xl font-bold text-[var(--color-text)] mb-3">What it handles</h2>
          <p className="text-[var(--color-text-muted)] mb-4">withPOISE covers 19 objection types across 5 categories:</p>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {[
              'Price & Budget objections',
              'Stalling & delaying tactics',
              'Competitor comparisons',
              'Scope & value challenges',
              'Trust & risk concerns',
            ].map(item => (
              <li key={item} className="flex items-center gap-2 text-sm text-[var(--color-text-muted)]">
                <span className="w-1.5 h-1.5 rounded-full bg-[var(--color-primary)] flex-shrink-0" />
                {item}
              </li>
            ))}
          </ul>
        </div>

        {/* The rule */}
        <div className="p-6 rounded-xl border border-[var(--color-primary)]/30 bg-[var(--color-primary)]/8 mb-10">
          <h2 className="text-lg font-bold text-[var(--color-text)] mb-2">The rule that never breaks</h2>
          <p className="text-[var(--color-text-muted)] text-sm leading-relaxed">
            Every response generated by withPOISE follows one absolute rule: <strong className="text-[var(--color-text)]">no discounts, ever.</strong> Not "consider offering a payment plan." Not "see if you can be flexible." The AI engine is built to hold your price, protect your positioning, and move the deal forward on value — not on concession.
          </p>
        </div>

        {/* Contact */}
        <div className="card mb-10">
          <h2 className="text-xl font-bold text-[var(--color-text)] mb-3">Contact</h2>
          <div className="space-y-1 text-sm text-[var(--color-text-muted)]">
            <p>PFA Dobre N Ana-Daniela</p>
            <p>Teiu 36, Argeș, Romania</p>
            <p>
              <a href="mailto:hello@withpoise.net" className="text-[var(--color-primary)] hover:underline">
                hello@withpoise.net
              </a>
            </p>
          </div>
        </div>

        {/* CTA */}
        <div className="text-center">
          <Link href="/register" className="btn-primary inline-flex items-center gap-2">
            Try withPOISE free — 5 responses included <ArrowRight className="w-4 h-4" />
          </Link>
        </div>

      </div>
    </div>
  )
}
